spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.4.192.38:3306/springbootweb?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: zhen202452
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
springbootweb:
  jwt:
    expire: 604800
    secret: f4e2g52034348f48b67cde581c0f9ec7
    header: token